joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    joint_1: {p: 500, d: 10, i: 0, i_clamp: 0}
    joint_2: {p: 500, d: 10, i: 0, i_clamp: 0}
    joint_3: {p: 500, d: 10, i: 0, i_clamp: 0}
    joint_4: {p: 300, d: 5, i: 0, i_clamp: 0}
    joint_5: {p: 300, d: 5, i: 0, i_clamp: 0}
    joint_6: {p: 200, d: 2, i: 0, i_clamp: 0}
